### ISSUE TITLE
Request for Custom OnePlus 11 Android System Image with Enhanced Root Access

### ISSUE THREAD

**Issue by dujianchi** [OnePlus-11-Development/android_device_oneplus_salami#1]
Hello, I'm looking to create a custom Android system image for the OnePlus 11. I have a specific requirement where my custom app needs read and write access to all files in the root directory (/). Additionally, I may need to execute common commands like tar, cp, rm, etc. Would it be possible for you to assist me with this? I am willing to provide compensation for your expertise. Thank you for your consideration.

**Comment by SetOfAllSets** [comment]
This is not the place to ask for help with that, this is a GitHub issue. If you really need it, just use magisk. Please close this issue.

**Comment by dujianchi** [comment]
Sorry to disturb you.
